# Generated by Django 5.2.8 on 2025-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
